[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "z"   # Optimize for size.
lto = true        # Enable Link Time Optimization.
codegen-units = 1 # Maximum optimization (slower build).
panic = "abort"   # Remove unwind tables (reduces size/metadata).
